//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NISC_MFP_MVC_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_logs_cardreader
    {
        public int serial { get; set; }
        public string cr_id { get; set; }
        public string card_id { get; set; }
        public Nullable<int> value { get; set; }
        public string seq_no { get; set; }
        public string login_type { get; set; }
        public Nullable<System.DateTime> log_time { get; set; }
        public Nullable<int> mfp_serial { get; set; }
    }
}
