//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NISC_MFP_MVC_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_mfp
    {
        public int serial { get; set; }
        public string cr_id { get; set; }
        public string printer_id { get; set; }
        public string driver_number { get; set; }
        public string mfp_ip { get; set; }
        public string mfp_name { get; set; }
        public string mfp_jt_name { get; set; }
        public string mfp_color { get; set; }
        public string mfp_status { get; set; }
        public int meter_num { get; set; }
        public Nullable<int> meter_current { get; set; }
        public Nullable<System.DateTime> meter_adjust_time { get; set; }
        public string login_card_id { get; set; }
    }
}
