//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NISC_MFP_MVC_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user
    {
        public int serial { get; set; }
        public string user_id { get; set; }
        public string user_password { get; set; }
        public string work_id { get; set; }
        public string user_name { get; set; }
        public string authority { get; set; }
        public string depositor { get; set; }
        public string dept_id { get; set; }
        public string import_flag { get; set; }
        public string color_enable_flag { get; set; }
        public string reserve_flag { get; set; }
        public string scan_reserve_flag { get; set; }
        public string personal_water_flag { get; set; }
        public string personal_water_depth { get; set; }
        public string e_mail { get; set; }
        public string if_deleted { get; set; }
        public string group_id { get; set; }
        public string copy_enable_flag { get; set; }
        public string print_enable_flag { get; set; }
        public string scan_enable_flag { get; set; }
        public string fax_enable_flag { get; set; }
    }
}
