//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NISC_MFP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_mng
    {
        public string doc_uid { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> ntime { get; set; }
        public string doc_name { get; set; }
        public string doc_ext { get; set; }
        public string page_size { get; set; }
        public Nullable<int> page_count { get; set; }
        public Nullable<int> is_user_del { get; set; }
        public Nullable<int> detail_count { get; set; }
        public Nullable<int> pkg_per { get; set; }
        public Nullable<int> duplexing { get; set; }
        public Nullable<int> inputbin { get; set; }
        public Nullable<int> copycount { get; set; }
        public Nullable<int> pageorientation { get; set; }
        public Nullable<int> is_print { get; set; }
        public Nullable<int> bc_print { get; set; }
        public string data_source { get; set; }
        public string file_ext { get; set; }
        public string prn_device { get; set; }
        public int is_upload { get; set; }
        public string loc_no { get; set; }
    }
}
