//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NISC_MFP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_card
    {
        public int serial { get; set; }
        public string card_id { get; set; }
        public string card_password { get; set; }
        public string card_type { get; set; }
        public string card_type2 { get; set; }
        public Nullable<int> value { get; set; }
        public int freevalue { get; set; }
        public string enable { get; set; }
        public string user_id { get; set; }
        public string import_flag { get; set; }
        public string if_deleted { get; set; }
    }
}
