//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NISC_MFP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pdfback
    {
        public int id { get; set; }
        public string timestamp { get; set; }
        public string username { get; set; }
        public string jobType { get; set; }
        public string serverName { get; set; }
        public string serverVersion { get; set; }
        public string printerAddr { get; set; }
        public string file { get; set; }
    }
}
