//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NISC_MFP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblusers
    {
        public int ID { get; set; }
        public string FULLNAME { get; set; }
        public string EMAIL { get; set; }
        public int IS_ACTIVE { get; set; }
        public string PWD { get; set; }
        public string LOGIN_TOKEN { get; set; }
        public string SCANSTORAGE { get; set; }
        public int CREDIT { get; set; }
        public string CODE { get; set; }
        public string SYNCSOURCE { get; set; }
        public string LANG { get; set; }
        public int SESSIONREFCNT { get; set; }
        public int QUOTAACTIVE { get; set; }
        public string PHONE { get; set; }
        public string NOTES { get; set; }
        public string AUTHSERVER { get; set; }
        public int USEAUTHSERVER { get; set; }
    }
}
