//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NISC_MFP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class watermark
    {
        public string pkey { get; set; }
        public string page_size { get; set; }
        public string wname { get; set; }
        public string wspeci { get; set; }
        public Nullable<System.DateTime> ntime { get; set; }
        public string ver { get; set; }
        public byte[] watermark1 { get; set; }
        public Nullable<int> is_active { get; set; }
    }
}
