//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NISC_MFP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_logs_print
    {
        public int serial { get; set; }
        public string dept_id { get; set; }
        public string dept_name { get; set; }
        public Nullable<int> dept_value { get; set; }
        public string user_id { get; set; }
        public string user_name { get; set; }
        public string work_id { get; set; }
        public string card_id { get; set; }
        public string card_type { get; set; }
        public string mfp_ip { get; set; }
        public string mfp_name { get; set; }
        public string computer { get; set; }
        public string user_computer_name { get; set; }
        public string driver_number { get; set; }
        public Nullable<int> value { get; set; }
        public Nullable<int> page { get; set; }
        public Nullable<int> copies { get; set; }
        public string page_color { get; set; }
        public string page_size { get; set; }
        public string duplex { get; set; }
        public string usage_type { get; set; }
        public Nullable<System.DateTime> print_date { get; set; }
        public string scan_destination { get; set; }
        public string document_name { get; set; }
        public string file_path { get; set; }
        public string file_name { get; set; }
        public string backup_label { get; set; }
        public string ocr { get; set; }
        public string remote_server_ip { get; set; }
        public string remote_server_name { get; set; }
        public Nullable<int> remote_server_serial { get; set; }
        public Nullable<int> mfp_meter_num_start { get; set; }
        public Nullable<int> mfp_meter_num_end { get; set; }
        public string upload_server { get; set; }
        public Nullable<int> job_id { get; set; }
    }
}
